### ISSUE TITLE
NPM install doesn't run the install script

### ISSUE THREAD

**Issue by smerrell** [TWExchangeSolutions/jira-precommit-hook#1]
Running `npm i jira-precommit-hook` doesn't end up copying the commit hook into the `.git/hooks` folder.

It looks like the `lib/install.js` folder might be assuming you're going to run the `bin/install` script from the root of your repo but NPM runs `bin/install` from the `node_modules/jira-precommit-hook`.

```
$ npm install jira-precommit-hook
\
> jira-precommit-hook@0.0.2 install ~/Projects/jira_project/node_modules/jira-precommit-hook
> node bin/install

jira-precommit-hook@0.0.2 node_modules/jira-precommit-hook
├── colors@1.1.0
├── fs-promise@0.3.1 (any-promise@0.1.0)
├── jira@0.9.2 (oauth@0.9.13, request@2.14.0)
└── lodash@3.9.3
```

**Comment by kthompson55** [comment]
Fixed in 0.0.3.
