### ISSUE TITLE
hook install fails

### ISSUE THREAD

**Issue by awedekind** [TWExchangeSolutions/jira-precommit-hook#13]
npm install jira-precommit-hook is failing to install
![image](https://cloud.githubusercontent.com/assets/3821676/7945179/5b8317d4-092c-11e5-8291-0da52cb20415.png)

**Comment by kthompson55** [comment]
Do you have a hooks folder inside of your .git directory?

**Comment by awedekind** [comment]
Just checked, and no, there is not hooks folder in my .git directory.

**Comment by kthompson55** [comment]
Could you please add one and try installing again?

**Comment by awedekind** [comment]
That worked, it's now installed. Thank you.

**Comment by kthompson55** [comment]
No problem. Thanks for reporting this.

**Comment by kthompson55** [comment]
To fix this issue, we are going to create a hooks folder in the event the client does not have one at the time of installation. It will be automatically created, without a prompt from the user.
