### ISSUE TITLE
Print commit message on failure

### ISSUE THREAD

**Issue by smerrell** [TWExchangeSolutions/jira-precommit-hook#19]
It would be useful to the commit hook to print out the commit message along with the fact that you had an error. The main reason behind this is most people will think their commit message is lost and have to type it again (which sucks if you write a descriptive commit message). It is available under `.git/COMMIT_EDITMSG`, but most people aren't going to think to look there.

so instead of:

```bash
$ git commit [type some long commit message in the editor]
$ Error: Must commit against at least one issue.
```

We get:

```bash
$ git commit [type some long commit message in the editor]
$ Commit Message:
This is a long commit message

that will be printed on multiple lines so you can easily copy
/ paste back into the editor and add a jira issue to.
Error: Must commit against at least one issue.
```

**Comment by mtscout6** [comment]
:+1:
