### ISSUE TITLE
Additional Info on Error

### ISSUE THREAD

**Issue by awedekind** [TWExchangeSolutions/jira-precommit-hook#23]
It would be nice to see additional information as to why the error occurred, specifically why I'm not able to commit against an issue. Currently all that is displayed is 
```
git commit -m "issueId"
Error: Cannot commit against this issue issueId
```
As a user I would like to know which criteria is missing that is preventing me from committing against an issue. (Missing manager approval, missing stakeholder approval, missing and initiative, epic needing to begin work)

**Comment by mtscout6** [comment]
This is in the bug-maintenance strategy, explain why you can't commit to the issue would be appropriate here.
