### ISSUE TITLE
Commit fails with "Cannot find module" message

### ISSUE THREAD

**Issue by bibodha** [TWExchangeSolutions/jira-precommit-hook#25]
npm install jira-precommit-hook
added jirarc
added node_modules to the gitignore file
commit with jira ticket number
![capture](https://cloud.githubusercontent.com/assets/2340572/8035831/e0fdc9f8-0db0-11e5-8dff-f500f9a154b0.PNG)

**Comment by mtscout6** [comment]
So it turned out that @bibodha's `.git/hooks` folder was a symlinked folder, which is why this happened. Detecting such in the install script would be pretty difficult since symlinks are fundamentally different between windows and mac. Probably best to rectify with some documentation in the readme.
