### ISSUE TITLE
Add 'Task' Issue type strategy

### ISSUE THREAD

**Issue by mtscout6** [TWExchangeSolutions/jira-precommit-hook#30]
This is a valid issue type that we have, the question that still stands though is what would the desired process for 'Task' be? Is it different than a 'Maintenance Task'? What's desired here?

/cc @shermanjoshua @RyanHauert

**Comment by shermanjoshua** [comment]
It is different than a maintenance task.  A 'Task' should not allow commits, as it is an item that is used to log the work performed against non-code related work (e.g. research, discovery, etc).
